apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: githubactions-task
  name: githubactions-task
spec:
  replicas: 5
  selector:
    matchLabels:
      app: githubactions-task
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: githubactions-task
        version: "2.0.0"
    spec:
      containers:
        - image: githubactions-task:9f3feda38e9e146a3e8e05a45ab0fc6290bac756
          name: githubactions-task
          ports:
            - name: http
              containerPort: 8050
