apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: githubactions-task
  name: githubactions-task
spec:
  replicas: 5
  selector:
    matchLabels:
      app: githubactions-task
  template:
    metadata:
      labels:
        app: githubactions-task
    spec:
      containers:
        - image: githubactions-task
          name: githubactions-task
          ports:
            - name: http
              containerPort: 8050
