apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: githubactions-task
  newName: kdbrener/githubactions-task
  newTag: latest
- name: githubactions-task
  newName: kdbrener/githubactions-task
  newTag: c231f4bf738535df912638b2f42b820fe250d0a6
