apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: githubactions-task
  newName: kdbrener/githubactions-task
  newTag: 4f19a1e7bb0713bbe41ee4881d30965400aa0cfc
namespace: python-app-blue
